### ISSUE TITLE
Filename lowercase in XGZP6897D.cpp?

### ISSUE THREAD

**Issue by KeesBlokland** [mstrens/oXs_on_RP2040#123]
Good morning all, did a quick compile for the latest version (2.12.28) and noticed that there is likely a naming issue in the XGZP6897D.cpp code.
Both XGZP6897D.cpp and XGZP6897D.h filenames use capitals, but there is a reference to 

src/XGZP6897D.cpp:1:10: fatal error: xgzp6897D.h:
#include "xgzp6897D.h"
and in params.cpp also.

Changing the filenames in the relevant files to uppercase solves it for me. 

as always, thanks for all the great work!

regards,
Kees

**Comment by mstrens** [comment]
Thanks for the feedback.
As I am on windows, I did not noticed it. 
It should be fixed in 2.11.29 (uploaded on github); now in lower case.

**Comment by KeesBlokland** [comment]
Thanks!
