### ISSUE TITLE
FeatureRequest: data logging on SDcard

### ISSUE THREAD

**Issue by NafetsRC** [mstrens/oXs_on_RP2040#17]
Hi there,

this is my first posting here. please advise, if this is the wrong place…

just successfully installed the compiled firmware. a gps module is already ordered 😉

i was looking and would appreciate a possibility to log all the data directly in the RC Model on MicroSD. Similar to JLog or SM gps logger 

Sorry, i can‘t examine, whether this would be technically possible or not

regards 
stefan

**Comment by pierrotm777** [comment]
May be with the add of an OpenLog module?
Good idea.

**Comment by fourfingers4** [comment]
I believe onboard logging is the only way to go if you want to use data for tuning or analysis. 
RC telemetry systems I have access to, won´t log better than 2Hz on vital parameters for later analysis, making data too blocky and unreliable.

**Comment by mstrens** [comment]
A logger functionality has been added to oXs (using a second RP2040).
Some users reported that it was OK.
If not, please open a new issue.
