### ISSUE TITLE
Rmp feature for Frsky 

### ISSUE THREAD

**Issue by pierrotm777** [mstrens/oXs_on_RP2040#2]
Salut Michel, 
Is it possible to add RPM feature for the Frsky S-Port protocol please,
Thanks,
Pierre

**Comment by mstrens** [comment]
Je devrais regarder comment faire.Le principal souci est que j'utilise déjà toutes les pins disponibles du RP2040-Zero.Il faudrait donc par exemple prendre une des 4 pins actuellement prévues pour mesurer les voltages.
Michel 
    Le mercredi 18 mai 2022, 18:38:10 UTC+2, pierrotm777 ***@***.***> a écrit :  
 
 


Salut Michel,
Is it possible to add RPM feature for the Frsky S-Port protocol please,
Thanks,
Pierre

**Comment by mstrens** [comment]
Bonjour Pierre,
J'ai ajouté rpm dans la nouvelle version que je viens de charger.
Michel
    Le mercredi 18 mai 2022, 18:38:10 UTC+2, pierrotm777 ***@***.***> a écrit :  
 
 


Salut Michel,
Is it possible to add RPM feature for the Frsky S-Port protocol please,
Thanks,
Pierre

**Comment by pierrotm777** [comment]
Salut Michel,
Je te remercie.
En attendant, j'ai réalisé un projet trouvé sur Rcgroups à base de Teensy
3.2, mais je vais regarder ça.

**Comment by pierrotm777** [comment]
Salut Michel,
Prendre une des 4 entrées analogiques ne me dérange pas. Je voudrais
réaliser un capteur rpm à base de capteur hall ou pris directement sur deux
fils de l'esc. Une dernière solution, lire la sortie pwm wun capteur
Hobbywing qui se connecte derrière un esc. La capteur hall serait le plus
universel à mon avis.
