### ISSUE TITLE
S.PORT telemetry protocol Voltage2/Current mA to A 

### ISSUE THREAD

**Issue by Satcomix** [mstrens/oXs_on_RP2040#41]
Hello Mstrens,
In HOTT Is everything OK, i checked twice.
I tried all possibilities to find out why in theTelemetry Display of my 
FrSky X20S Ethos S.PORT **the value 1650mA is shown as 165.1A.**
I also looked for a formula for Voltage2 to Current/100 in Platformio but only found something for Voltage (Voltage/10).

"fields per protocol.txt"
VOLT1       0.001V                 V1 pin is defined         VFAS (0x0210)   0.01V  (=10mV)
VOLT2       0.001V=0.001A    V2 pin is defined      Current (0x0200)   0.001A (=1mA)

processing cmd

Cmd to execute:   

Version = 1.1.0 
    Function                Pin   Change entering XXX=yyy (yyy=255 to disable)
Primary channels input    =    5  (PRI     = 5, 9, 21, 25)
Secondary channels input  =    1  (SEC     = 1, 13, 17, 29)
Telemetry . . . . . . . . =    0  (TLM     = 0, 1, 2, ..., 29)
GPS Rx  . . . . . . . . . =   12  (GPS_RX  = 0, 1, 2, ..., 29)
GPS Tx  . . . . . . . . . =   13  (GPS_TX  = 0, 1, 2, ..., 29)
Sbus OUT  . . . . . . . . =    2  (SBUS_OUT= 0, 1, 2, ..., 29)
RPM   . . . . . . . . . . =  255  (RPM     = 0, 1, 2, ..., 29)
SDA (I2C sensors) . . . . =   14  (SDA     = 2, 6, 10, 14, 18, 22, 26)
SCL (I2C sensors) . . . . =   15  (SCL     = 3, 7, 11, 15, 19, 23, 27)
PWM Channels 1, 2, 3 ,4   =  255  255    6  255 (C1 / C16= 0, 1, 2, ..., 15)
PWM Channels 5, 6, 7 ,8   =  255  255  255  255
PWM Channels 9,10,11,12   =  255  255  255  255
PWM Channels 13,14,15,16  =  255  255  255  255
Voltage 1, 2, 3, 4        =   26   27   28   29 (V1 / V4 = 26, 27, 28, 29)

Protocol is Sport (Frsky)
CRSF baudrate = 420000
Voltage parameters:
    Scales : 1.000000 , 1.000000 , 0.100000 , 0.100000 
    Offsets: 0.000000 , 0.000000 , 0.000000 , 0.000000 
    Temperature sensors are connected on V3 and V4
RPM multiplier = 1.000000
Baro sensor is detected using BMP280
    Sensitivity min = 100 (at 100)   , max = 300 (at 1000)
    Hysteresis = 5 
Acc/Gyro is detected using MP6050
     Acceleration offsets X, Y, Z = 0 , 0 , 0
     Gyro offsets         X, Y, Z = 0 , 0 , 0
First analog to digital sensor is not detected
Second analog to digital sensor is not detected
Foreseen GPS type is Ublox  :GPS is detected and has a fix
Failsafe uses predefined values
     Chan 1...4  = 976 , 992 , 992 , 992
     Chan 5...8  = 992 , 992 , 992 , 992
     Chan 9...12 = 992 , 992 , 992 , 992
     Chan 13...16= 992 , 992 , 992 , 992

Config parameters are OK
Press ? + Enter to get help about the commands

 >> 
processing cmd

Cmd to execute:   FV

GPS Latitude = 51.xxxxxxxx degree
GPS Longitude = 6.xxxxxxxx degree
GPS Groundspeed = 5 cm/s
GPS Heading = 125.470000 degree
GPS Altitude = 3808 cm
GPS Num sat. = 109 cm
GPS Date J M A = 14 2 23 
GPS Time H M S = 13 50 6 
GPS Pdop = 183 
GPS Home bearing = 105 degree
GPS Home distance = 8 m
Volt 1 = 1675 mVolt
**Current (Volt 2) = 1650 mA  shown in the Handheld Display as 165,0 Ampere**
Capacity (using current) = 0 mAh
Temp 1 (Volt 3) = 164 degree
Temp 2 (Volt 4) = 26 degree
Vspeed = 1 cm/s
Baro Rel altitude = 25 cm
Pitch = 2 degree
Roll = 1 degree

br,
Torsten

**Comment by Satcomix** [comment]
The same also applies to V3, V4

Version = 1.1.0 
    Function                Pin   Change entering XXX=yyy (yyy=255 to disable)
Primary channels input    =    5  (PRI     = 5, 9, 21, 25)
Secondary channels input  =    1  (SEC     = 1, 13, 17, 29)
Telemetry . . . . . . . . =    0  (TLM     = 0, 1, 2, ..., 29)
GPS Rx  . . . . . . . . . =   12  (GPS_RX  = 0, 1, 2, ..., 29)
GPS Tx  . . . . . . . . . =   13  (GPS_TX  = 0, 1, 2, ..., 29)
Sbus OUT  . . . . . . . . =    2  (SBUS_OUT= 0, 1, 2, ..., 29)
RPM   . . . . . . . . . . =  255  (RPM     = 0, 1, 2, ..., 29)
SDA (I2C sensors) . . . . =   14  (SDA     = 2, 6, 10, 14, 18, 22, 26)
SCL (I2C sensors) . . . . =   15  (SCL     = 3, 7, 11, 15, 19, 23, 27)
PWM Channels 1, 2, 3 ,4   =  255  255    6  255 (C1 / C16= 0, 1, 2, ..., 15)
PWM Channels 5, 6, 7 ,8   =  255  255  255  255
PWM Channels 9,10,11,12   =  255  255  255  255
PWM Channels 13,14,15,16  =  255  255  255  255
Voltage 1, 2, 3, 4        =   26   27   28   29 (V1 / V4 = 26, 27, 28, 29)

Protocol is Sport (Frsky)
CRSF baudrate = 420000
Voltage parameters:
    Scales : 1.000000 , 1.000000 , 1.000000 , 1.000000 
    Offsets: 0.000000 , 0.000000 , 0.000000 , 0.000000 
    No temperature sensors are connected on V3 and V4
RPM multiplier = 1.000000
Baro sensor is detected using BMP280
    Sensitivity min = 100 (at 100)   , max = 300 (at 1000)
    Hysteresis = 5 
Acc/Gyro is detected using MP6050
     Acceleration offsets X, Y, Z = 0 , 0 , 0
     Gyro offsets         X, Y, Z = 0 , 0 , 0
First analog to digital sensor is not detected
Second analog to digital sensor is not detected
Foreseen GPS type is Ublox  :GPS is detected and has a fix
Failsafe uses predefined values
     Chan 1...4  = 976 , 992 , 992 , 992
     Chan 5...8  = 992 , 992 , 992 , 992
     Chan 9...12 = 992 , 992 , 992 , 992
     Chan 13...16= 992 , 992 , 992 , 992

Config parameters are OK
Press ? + Enter to get help about the commands

 >> 
processing cmd

Cmd to execute:   FV

GPS Latitude = 51.xxxxxxxx degree
GPS Longitude = 6.xxxxxxxx degree
GPS Groundspeed = 17 cm/s
GPS Heading = 313.550000 degree
GPS Altitude = 2758 cm
GPS Num sat. = 111 cm
GPS Date J M A = 14 2 23 
GPS Time H M S = 15 55 52 
GPS Pdop = 186 
GPS Home bearing = 312 degree
GPS Home distance = 39 m
Volt 1 = 1675 mVolt --------->Telemetry Display 1,67V
**Current (Volt 2) = 1651 mA -->Telemetry Display FASS 165.0A
Volt 3 = 1646 mVolt --------->Telemetry Display Volt3 1645V
Volt 4 = 260 mVolt ----------> Telemtry Display Volt4 260V**
Capacity (using current) = 0 mAh
Vspeed = 7 cm/s
Baro Rel altitude = 0 cm
Pitch = 2 degree
Roll = 1 degree
br,
Torsten

**Comment by mstrens** [comment]
For current, I think it is fixed in version 1.1.1 now on github test branch.

For Volt3 and Volt4, I presume it is OK to keep it as it is currently..
Currently oXs transmits the value as it is stored internally (so no reformatting when sent over sport)
For those fields I use a "DIY" field ID. So I expect that for such a field, openTX (or others) does not assign automatically a unit. It is up to the user to decide the unit depending on the physical aspect that is converted to a voltage for the RP2040. I expect that the user can select the unit and number of decimals on the handset.

**Comment by Satcomix** [comment]
Hello Mstrens,
It works,
FASS is OK,
for the DIY Sensors i will use SCALE.
I will close the Issue.
Thank you very much.
br,
Torsten
