### ISSUE TITLE
V1/V2 test under 1.1.5 with MPX and ELRS

### ISSUE THREAD

**Issue by nostromo123** [mstrens/oXs_on_RP2040#46]
Not really an issue, but more or less a question.

I am testing V1/V2 here by putting 1.6V on the inputs.

On MPX values show up on the radio as 1.6V / 1.6A.

On ELRS there is a factor 100 in the displayed values.

In CONFIG no modification, but standard. On radio side also no modification.

Is that factor 100 seen with ELRS intention or ....? 

br - KH

**Comment by mstrens** [comment]
I just saw that elrs expect values in 0.1V and 0.1A.
So, I will divide the values by 100 in next version (for ELRS)

**Comment by nostromo123** [comment]
Checked it with 1.2.2

V1/V2 in ELRS is fine now. 

THX - KH
