### ISSUE TITLE
FrSky F.PORT

### ISSUE THREAD

**Issue by Satcomix** [mstrens/oXs_on_RP2040#57]
Hello Mstrens,
As promised, today I was looking for information for the F.PORT Protocol.
I hope there is something worthwhile in there.
https://www.propwashed.com/wp-content/uploads/2018/01/F.Port_.protocol.betaFlight.V2.1.2017.11.21.pdf

https://github.com/betaflight/betaflight/blob/master/src/main/rx/fport.c

https://ardupilot.org/copter/docs/common-connecting-sport-fport.html

https://inavfixedwinggroup.com/guides/getting-started/frsky-protocols-made-simple/#46-fport

https://oscarliang.com/setup-frsky-fport/

https://lubin.kerhuel.eu/uxv/block-receiver-telemetry/

https://www.multirotorguide.com/news/frsky-fport-2-f-port-2-0-upgraded-protocol/

https://manual.spirit-system.com/index.php?title=FrSky_FPort
Greeting,
Torsten

**Comment by mstrens** [comment]
Thanks,
The first link is clear.
I will think about how to best implement it (using hardware uart or using pio UART).
