### ISSUE TITLE
Jeti DC16 and RX R9 No telemetry display information

### ISSUE THREAD

**Issue by aepub** [mstrens/oXs_on_RP2040#69]
For the first time, I used the oXs, Jeti's DC16 remote control, RX 9-channel receiver, RP2040 to connect to Beitian 220GPS and GY63's MS5611. After brushing uf2 to RP2040, no GPS or MS5611 were found on the remote control display.

Is the line between my RP2040 and the receiver incorrect? "
I connected the Ext signal line of the R9 receiver to the Telemetry of the RP2040, which is also called Gpio2（TLM=2）. 
The green light of the RP2040 flashes.".

My profile is:
---------------------------------------------------
Version = 1.4.3 
    Function                Pin   Change entering XXX=yyy (yyy=255 to disable)
Primary channels input    =  255  (PRI     = 5, 9, 21, 25)
Secondary channels input  =  255  (SEC     = 1, 13, 17, 29)
Telemetry . . . . . . . . =    2  (TLM     = 0, 1, 2, ..., 29)
GPS Rx  . . . . . . . . . =   28  (GPS_RX  = 0, 1, 2, ..., 29)
GPS Tx  . . . . . . . . . =   29  (GPS_TX  = 0, 1, 2, ..., 29)
Sbus OUT  . . . . . . . . =  255  (SBUS_OUT= 0, 1, 2, ..., 29)
RPM   . . . . . . . . . . =  255  (RPM     = 0, 1, 2, ..., 29)
SDA (I2C sensors) . . . . =    6  (SDA     = 2, 6, 10, 14, 18, 22, 26)
SCL (I2C sensors) . . . . =    7  (SCL     = 3, 7, 11, 15, 19, 23, 27)
PWM Channels 1, 2, 3 ,4   =  255  255  255  255 (C1 / C16= 0, 1, 2, ..., 15)
PWM Channels 5, 6, 7 ,8   =  255  255  255  255
PWM Channels 9,10,11,12   =  255  255  255  255
PWM Channels 13,14,15,16  =  255  255  255  255
Voltage 1, 2, 3, 4        =  255  255  255  255 (V1 / V4 = 26, 27, 28, 29)

Protocol is Jeti (Ex)
CRSF baudrate = 420000
Voltage parameters:
    Scales : 1.000000 , 1.000000 , 1.000000 , 1.000000 
    Offsets: 0.000000 , 0.000000 , 0.000000 , 0.000000 
    No temperature sensors are connected on V3 and V4
RPM multiplier = 1.000000
Baro sensor is detected using MS5611
    Sensitivity min = 100 (at 100)   , max = 300 (at 1000)
    Hysteresis = 5 
Acc/Gyro is not detected
First analog to digital sensor is not detected
Second analog to digital sensor is not detected
Foreseen GPS type is Ublox  :GPS is detected and has a fix
Failsafe type is HOLD

Config parameters are OK
Press ? + Enter to get help about the commands
-------------------------------------------------------------
EX BUS is set on the remote control
![1](https://user-images.githubusercontent.com/44573941/228221562-fa5f3c3b-b702-4978-bfb9-e24b4b1777d9.jpg)
![2](https://user-images.githubusercontent.com/44573941/228221607-7e71bc98-2814-41b9-9b15-5fca5d6c3b5a.jpg)
![3](https://user-images.githubusercontent.com/44573941/228221672-7c3d9071-be15-4f1d-9319-e13fc11da15a.jpg)

**Comment by mstrens** [comment]
oXs uses the Jeti EX protocol (not the EXbus)
Here the description that I found

“EXbus” is the third evolutionary stage of JETI telemetry following JETI v1 and JETI EX. EXbus is again not a “bus”.
JETI v1 was pure text, – about every 100ms 16 x 2 characters, then a 1-byte response of the terminal (“box”) to the sensor containing the code of 4 keys. This text mode can therefore be used for interactive applications (as with HoTT text mode as well).
Then came JETI EX: Another type “hidden message” (introduced in v1 for sensor alarms) by means of which the sensor defines its displays, – textually (display name and unit of measurement) and binary (data type). Then data is transmitted binary with reference to the respective display. – EX includes (encapsulates) the text mode which exists independently next to it.
Both protocols work with only 9k6.
Now EXbus was introduced which is also only a point-to-point connection, no bus. Only several ports on a REX receiver connected to EXbus will result in a virtual “bus”. – By the way, a REX integrates an expander via several “ports” assigned to “JETIbox” which previously did not really work for multiplex between EX-speaking sensors connected to a dedicated device “EX Expander”, – with a REX it works.
EXbus impresses with 125 or 250kBd, whereby so far only devices can be seen which speak 125kBd. The master (REX) dictates the speed, a sensor must react adaptively.
