### ISSUE TITLE
Error compiling source code

### ISSUE THREAD

**Issue by aepub** [mstrens/oXs_on_RP2040#70]
I tried to compile it myself. The Arduino IDE 2.0.4 and WIZIO extension (the url address has already been specified by the https://github.com/Wiz-IO/wizio-pico Become https://github.com/Wiz-IO/wizio-arduino-pico ）

However, an error occurred during compilation: 
Compilation error: 'int16_ t' does not name a type; did you mean '__ int16_ t'?
![error](https://user-images.githubusercontent.com/44573941/228419007-445fe633-69ff-4b95-ba5f-bbdd0ba85781.jpg)

**Comment by mstrens** [comment]
It is developped using Vscode and platformIo.
I expect you have to install those tools.
I think I do not use Arduino functions but only the RP2040 SDK.

**Comment by mstrens** [comment]
Note: if you just want to use the project, you do not need to compile your self.
You can just flash (drag and drop) the uf2 file that is provided. You must then only use an serial terminal to send parameters via USB

**Comment by mstrens** [comment]
It is a long time ago that I installed it.
I do not remember exactly how I proceeded.
I see (now) that it is available here
https://github.com/Wiz-IO/framework-wizio-pico

Please note that you have to install all the file that are in the oXs project in te same dir structure as on github.
This contains the file platformio.ini file that I use.

**Comment by maxgerhardt** [comment]
@mstrens can I ask you the favor of uploading your current `C:\Users\<user>\.platformio\platforms\wizio-pico` folder somewhere? You might have a later version than most.

**Comment by maxgerhardt** [comment]
>Will it be enough to just upload this folder? 

Yes because [all other repos](https://community.platformio.org/t/solved-can-not-install-https-github-com-wiz-io-wizio-pico-1-post-here-please-help/30716/8?u=maxgerhardt) in are still up.

**Comment by mstrens** [comment]
I am currently testing a new process that does not use platformio anymore.
Currently I can compile (inside vscode) but I did not yet tested the result.
If OK, I will first put in a new branch (for testing)

**Comment by mstrens** [comment]
It seems to work (just a simple test).
I created a new branch named no_wizio.

To try, I suggest:
1- to install the tools ( RP2040+Vscode) using this link
https://github.com/raspberrypi/pico-setup-windows/blob/master/docs/tutorial.md
It is just one exe to run.
2- to install the oXs firmware (from github in branch no-wizio)
3- as explained in the tutorial from point 1, ( for new project)
Launch VS Code from the Pico - Visual Studio Code shortcut in the Start Menu, and then open your new project folder.

Configure the project by running the CMake: Configure command from VS Code's command palette.

Build and debug the project as described in previous sections.

Please note that uf2 file to be copied in the RP2040 is generated in the subdirectory "build"

**Comment by maxgerhardt** [comment]
I'm totally fine with your decision to not use PlatformIO in this project anymore, I just wish to at least preserve or maintain the wizio-pico repository for anyone desperately needing it -- did you have a chance to zip + upload your local `wizio-pico` yet?

**Comment by mstrens** [comment]
For safety, I now zip wizio-pico folder and I saved it in folder "doc" from branch "test"

**Comment by Satcomix** [comment]
Hello Mstrens,
I downloaded and installed pico_setup_windows.
Then I downloaded and unpacked your .zip file from the new branch.
Where do I have to paste this unpacked oXs_RP2040_no_wizio folder???
Greeting,
Torsten

**Comment by mstrens** [comment]
How do you proceed usually?
I presume there are 2 main ways to proceed with gihub.
- or you download a zip file from github and you install it where you want. Then you open vscode and in the menu "File" you select the item "open folder" in the list. The drawback of this method is that each time there is a new version, you have to download the zip file again, deleted the content of the folder and replace it with the unzip.
- or you create a local repository of the github in the folder that you want. Then each time there is a new version, you can just ask for synchronization. I do not know the detail of how to proceed but I expect there are tutorial on the web.
Note : as vscode support git, there are some commands/buttons inside vcode to manage easily the syncrhronisation.

**Comment by Satcomix** [comment]
I usually go the first way you point out.
Download the .zip and then copied to the Platformio Projects folder.

**Comment by mstrens** [comment]
No problem. I expect you can continue this way if you prefer.

**Comment by maxgerhardt** [comment]
Thanks for zip, I have it now up and running again at https://github.com/maxgerhardt/wizio-pico again, but had to add a build fix to exclude Raspberry Pi Pico W source files.

Just change the `platformio.ini` to

```ini
platform = https://github.com/maxgerhardt/wizio-pico.git
```
and it should build again.
```
Checking size .pio\build\raspberry-mstrens\APPLICATION.elf
Building .pio\build\raspberry-mstrens\APPLICATION.bin
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [=         ]  14.4% (used 37644 bytes from 262144 bytes)
Flash: [=         ]   6.3% (used 132608 bytes from 2097152 bytes)
DONE
```

**Comment by Satcomix** [comment]
Hello Mstrens,
After a new installation of pico_setup_windows, I was able to successfully create my first CMake oXs build Ver.2.1.1.
The first build took a while, but the second is pretty quick.
**Thank you for your support and description of installing CMake and how to create your own build.**

processing cmd

Cmd to execute:   

**Version = 2.1.1** 
    Function                Pin   Change entering XXX=yyy (yyy=255 to disable)
Primary channels input    =    5  (PRI     = 5, 9, 21, 25)
Secondary channels input  =  255  (SEC     = 1, 13, 17, 29)
Telemetry . . . . . . . . =  255  (TLM     = 0, 1, 2, ..., 29)
GPS Rx  . . . . . . . . . =   12  (GPS_RX  = 0, 1, 2, ..., 29)
GPS Tx  . . . . . . . . . =   13  (GPS_TX  = 0, 1, 2, ..., 29)
Sbus OUT  . . . . . . . . =    2  (SBUS_OUT= 0, 1, 2, ..., 29)
RPM   . . . . . . . . . . =    4  (RPM     = 0, 1, 2, ..., 29)
SDA (I2C sensors) . . . . =   14  (SDA     = 2, 6, 10, 14, 18, 22, 26)
SCL (I2C sensors) . . . . =   15  (SCL     = 3, 7, 11, 15, 19, 23, 27)
PWM Channels 1, 2, 3 ,4   =  255  255    6    7 (C1 / C16= 0, 1, 2, ..., 15)
PWM Channels 5, 6, 7 ,8   =  255  255  255  255
PWM Channels 9,10,11,12   =  255  255  255  255
PWM Channels 13,14,15,16  =  255  255  255  255
Voltage 1, 2, 3, 4        =   26   27   28   29 (V1 / V4 = 26, 27, 28, 29)

Protocol is Fbus(Frsky)

br, 
Torsten
