### ISSUE TITLE
Pitch and roll with decimal possible?

### ISSUE THREAD

**Issue by Allerhopp** [mstrens/oXs_on_RP2040#84]
It would be great to have a better resolution for pitch and roll using smartport. We want to measure angle of attack changes with a glider.

**Comment by Allerhopp** [comment]
I am not able to find the part of the code where pitch and roll are clipped to one byte. This is necessary for CRSF, but not for smartport DIY-sensors. Any hints please, where I can multiply pitch and roll with 100? That would fill my needs ...

**Comment by mstrens** [comment]
I just made a change to get  2 decimals in sport and fbus for roll and pitch.
It is in test branch 2.5.9

**Comment by Allerhopp** [comment]
Thank you Michel for the fast response!
I get now +/- 100, 200, 300 ..... tilting 1, 2, or 3°
and with decimals 0.00 I get 
+/- 1.00, 2.00, 3.00
Seems there is another piece of code limiting the resolution?

**Comment by mstrens** [comment]
I think I understand what happened.
Can you test with 2.5.10 version.

**Comment by Allerhopp** [comment]
Thanks, this change works perfectly!
Btw. the noise is lower than +/- 0.04° which is better than expected.

**Comment by mstrens** [comment]
Indeed, I expected more noise. That is the reason why I initially had no decimals.

**Comment by Allerhopp** [comment]
Now we can continue measuring. FYI this is our newly designed Prandtl nozzle for SDP-sensors.
![Prandtl2-2](https://github.com/mstrens/oXs_on_RP2040/assets/23188713/ed175486-1dc2-4a38-b6bd-beb989170391)
